{{- if (.Values.sealedSecrets | default dict).enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "cue.fullname" . }}-backend-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cue.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.secret }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ include "cue.fullname" . }}-backend-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}